<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cli\Module'                        => __DIR__ . '/Module.php',
    'Cli\Controller\CliController' => __DIR__ . '/src/Cli/Controller/CliController.php',
    'CliTest\Framework\TestCase'        => __DIR__ . '/tests/Cli/Framework/TestCase.php',
    'CliTest\SampleTest'                => __DIR__ . '/tests/Cli/SampleTest.php',
);
